someText = "This is a text."

print(someText.endswith("ext"))
print(someText.endswith("ext."))
print("------2.----------------------")
print(someText.islower())
print("------3.----------------------")
print(someText.upper())
print(someText.upper().isupper())
print("------4.-----------------------")
print(someText.find("is"))
print(someText.find("is", 3))
print("------5.------------------------")
print(someText.replace("a", "4"))
print(someText.replace("a", "4").replace("e", "6"))
print("------6.-------------------------")
print(someText.split(" "))
print("------7.-------------------------")
somethingLikeNumber = "1000"
print(somethingLikeNumber.isdigit())
print(somethingLikeNumber.isdecimal())
print("------8.-------------------------")
print(somethingLikeNumber.isalpha())
print(somethingLikeNumber.isalnum())
print("------End lesson-----")

# Laboratory
quote = "A good programmer is someone who always looks " \
        "both ways before crossing a one-way street"
print(quote.upper())
print(quote.lower())
print(quote.endswith("street"))
print(quote.islower())
print(quote.upper().isupper())
print(quote.find("one"))
print(quote.replace("one", "1"))
print(quote.replace("one", "1").replace("both", "2"))
print(quote.split(" "))
print(quote.isdigit())
print(quote.isdecimal())
print(quote.isalpha())
print(quote.isalnum())
